
const fs = require('fs');
const path = require('path');

function readImageBase64(filePath) {
    const fullPath = path.join(__dirname, filePath);
  
    try {
      const imageBuffer = fs.readFileSync(fullPath);
      const base64Image = imageBuffer.toString('base64');
  
      const extension = path.extname(filePath).toLowerCase();
      const mimeTypes = {
        '.svg': 'image/svg+xml',
        '.png': 'image/png',
        '.jpg': 'image/jpeg',
        '.jpeg': 'image/jpeg',
      };
      const mimeType = mimeTypes[extension] || 'application/octet-stream';
  
      return `data:${mimeType};base64,${base64Image}`;
    } catch (error) {
      console.error(`Error al leer la imagen ${filePath}: ${error.message}`);
      return null;
    }
  }

  
const stores = [{
    image: readImageBase64('./assets/icon/essay-writer.svg'),
    fav: false,
    title: 'AI Essay Writer',
    description: 'Write a professional essay with an in-depth vision, covering everything and using any reference style you need.'
},{
    image: readImageBase64('./assets/icon/essaychecker.svg'),
    fav: false,
    title: 'Essay Checker',
    description: 'Verify the organization, clarity, and overall quality of an essay to ensure proper structure.'
},{
    image: readImageBase64('./assets/icon/essayrewriter-icon-01.svg'),
    fav: false,
    title: 'Essay Rewriter',
    description: 'Rewrite your essay to make it plagiarism-free and convey a stronger sense of professionalism.'
},{
    image: readImageBase64('./assets/icon/hook-generator.svg'),
    fav: false,
    title: 'Essay Hook Generator',
    description: 'Hook your readers from the start with our AI-powered essay hook generator.'
},{
    image: readImageBase64('./assets/icon/essay-extender.svg'),
    fav: false,
    title: 'Essay Extender',
    description: 'Expand your essay content to deepen your arguments and broaden your discussions.'
},{
    image: readImageBase64('./assets/icon/essay-introduction.svg'),
    fav: false,
    title: 'Essay Introduction Generator',
    description: 'Make a lasting first impression with our AI-powered essay introduction generator.'
},



{
    image: readImageBase64('./assets/icon/research-paper.svg'),
    fav: false,
    title: 'Research Paper Summarizer',
    description: 'Simplify complex research with AI-driven summaries, enhancing productivity and comprehension alike.'
},{
    image: readImageBase64('./assets/icon/casestudy-icon-01.svg'),
    fav: false,
    title: 'Case Study Summarizer',
    description: 'Condense case studies into concise insights, empowering data-driven decision learning.'
},{
    image: readImageBase64('./assets/icon/conclusiongenerator.svg'),
    fav: false,
    title: 'Essay Conclusion Generator',
    description: 'Wrap up your writing with impactful, resonant conclusions generated by AI.'
},{
    image: readImageBase64('./assets/icon/thesisstatement-icon-01.svg'),
    fav: false,
    title: 'Thesis Statement Generator',
    description: 'Level up your academic writing with excellent thesis statements.'
},{
    image: readImageBase64('./assets/icon/research-title-generator.svg'),
    fav: false,
    title: 'Research Title Generator',
    description: 'Unlock your research potential with our cutting-edge Research Title Generator.'
},{
    image: readImageBase64('./assets/icon/essayshortener-icon-01.svg'),
    fav: false,
    title: 'Essay Shortener',
    description: 'Transform lengthy essays into concise, impactful pieces with AI-driven content reduction.'
},




{
    image: readImageBase64('./assets/icon/paraphrasingtool.svg'),
    fav: false,
    title: 'Paraphrasing Tool',
    description: 'Advanced paraphrasing tool that not just simply rephrases your content but also enhances its overall quality.'
},{
    image: readImageBase64('./assets/icon/article-rewrite.svg'),
    fav: false,
    title: 'Article Rewriter',
    description: 'Rewrite and transform your article into an irresistible masterpiece that captivates readers and preserves its originality.'
},{
    image: readImageBase64('./assets/icon/summarizer.svg'),
    fav: false,
    title: 'Text & PDF Summarizer',
    description: 'Identify and correct grammatical errors to improve clarity, conciseness, and credibility in any written work.'
},{
    image: readImageBase64('./assets/icon/ai-paragraph-rewrite.svg'),
    fav: false,
    title: 'AI Paragraph Rewriter',
    description: 'Refresh and enhance your paragraphs for better readability and audience engagement.'
},{
    image: readImageBase64('./assets/icon/profreader.svg'),
    fav: false,
    title: 'Proofreader',
    description: 'Revise a text for grammar, spelling, punctuation, or formatting errors to enhance clarity.'
},


{
    image: readImageBase64('./assets/icon/ai-email.svg'),
    fav: false,
    title: 'AI Email Writer',
    description: 'Create personalized and engaging emails quickly and easily with our advanced AI-power tool.'
},{
    image: readImageBase64('./assets/icon/ai-email.svg'),
    fav: false,
    title: 'Email Subject Line Generator',
    description: 'Create captivating and optimized email subject lines to give your business a boost.'
},{
    image: readImageBase64('./assets/icon/coldemail-icon-01.svg'),
    fav: false,
    title: 'Cold Email Generator',
    description: 'Increase response rates with compelling cold emails, opening doors to new business opportunities.'
},{
    image: readImageBase64('./assets/icon/marketing-email.svg'),
    fav: false,
    title: 'Marketing Email Generator',
    description: 'Boost your campaigns with eye-catching marketing emails, optimized for conversion.'
},{
    image: readImageBase64('./assets/icon/thank-you-letter.svg'),
    fav: false,
    title: 'Thank You Letter Generator',
    description: 'Show your appreciation with heartfelt thank you letters tailored to your needs.'
},


{
    image: readImageBase64('./assets/icon/hashtaggenerate.svg'),
    fav: false,
    title: 'Hashtag Generator',
    description: 'Generate creative and relevant hashtags to amplify your contents reach.'
},{
    image: readImageBase64('./assets/icon/tweet-generator.svg'),
    fav: false,
    title: 'Tweet & Threads Generator',
    description: 'Make entertaining tweets to keep your followers interested.'
},{
    image: readImageBase64('./assets/icon/facebook-generator.svg'),
    fav: false,
    title: 'Facebook Ad Copy Generator',
    description: 'Elaborate appealing copy based on your needs of Facebook Ads copy text.'
},{
    image: readImageBase64('./assets/icon/scriptgenerator-icon-01.svg'),
    fav: false,
    title: 'Script Generator',
    description: 'Attract your audience with unique and compelling scripts that reflect your personality.'
},{
    image: readImageBase64('./assets/icon/company-biogenerator.svg'),
    fav: false,
    title: 'Company Bio Generator',
    description: 'Write appealing and convincing bios that will arise your readers interest.'
},{
    image: readImageBase64('./assets/icon/linkedin-generator.svg'),
    fav: false,
    title: 'Linkedin Headline Generator',
    description: 'Distinguish your LinkedIn profile with a compelling headline.'
},{
    image: readImageBase64('./assets/icon/linkedin-generator.svg'),
    fav: false,
    title: 'Google Ad Copy Generator',
    description: 'Develop effective descriptions for your Google Search Ads to increase conversion.'
},


{
    image: readImageBase64('./assets/icon/product-design.svg'),
    fav: false,
    title: 'Product Description Generator',
    description: 'Craft engaging, persuasive descriptions using AI-generated content.'
},{
    image: readImageBase64('./assets/icon/amazon-icon-01.svg'),
    fav: false,
    title: 'Amazon Product Description Generator',
    description: 'Drive sales with SEO-optimized descriptions, maximizing visibility and customer engagement.'
},{
    image: readImageBase64('./assets/icon/shopify-icon-01.svg'),
    fav: false,
    title: 'Shopify Product Description Generator',
    description: 'Optimize your Shopify store with persuasive descriptions and elevate your brand.'
},{
    image: readImageBase64('./assets/icon/etsy-icon-01.svg'),
    fav: false,
    title: 'Etsy Product Description Generator',
    description: 'Entice potential buyers on Etsy with informative product descriptions that reflect your passion and creativity.'
},{
    image: readImageBase64('./assets/icon/testimonialgenerator-icon-01.svg'),
    fav: false,
    title: 'Testimonials / Reviews Generator',
    description: 'Boost credibility with authentic, persuasive testimonials, attracting customers and fostering trust.'
},{
    image: readImageBase64('./assets/icon/storyideagenerator-icon-01.svg'),
    fav: false,
    title: 'Store Description Generator',
    description: 'Define your store with a unique, engaging description, effortlessly conveying its value proposition.'
},{
    image: readImageBase64('./assets/icon/flipkart-icon-01.svg'),
    fav: false,
    title: 'Flipkart Product Description Generator',
    description: 'Enhance your listings with captivating descriptions, enticing customers to choose your products.'
},{
    image: readImageBase64('./assets/icon/features-benefit.svg'),
    fav: false,
    title: 'Features to Benefit Converter',
    description: 'Highlighting the features of your product as well as benefits to boost sales.'
},{
    image: readImageBase64('./assets/icon/value-proposition.svg'),
    fav: false,
    title: 'Value Proposition Generator',
    description: 'Create a strong statement that describes the nature of your product and highlights its significance.'
},{
    image: readImageBase64('./assets/icon/productfeaturesgenerator.svg'),
    fav: false,
    title: 'Product Features Generator',
    description: 'Create detailed and enticing descriptions of your products features, potentially improving your product visibility and driving more sales.'
},{
    image: readImageBase64('./assets/icon/product-name-generator.svg'),
    fav: false,
    title: 'Product Name Generator',
    description: 'Create unique, catchy names for your product, capturing its essence and sparking customer interest.'
},{
    image: readImageBase64('./assets/icon/cus-ai-business-name-generator.svg'),
    fav: false,
    title: 'AI Business Name Generator',
    description: 'Use artificial intelligence to design distinct and memorable business names that resonate with your target audience.'
}]



module.exports = stores